celebrity= input("Give me a name of a celebrity ")
first_adjective= input("Give me an adjective ")
first_noun= input("Give me a noun ")
second_noun= input("Give me another noun ")
first_plural_noun= input("Give me a plural noun ")
third_noun= input("Give me another noun ")
past_verb= input("Give me a past tense verb ")
fourth_noun= input("Give me another noun ")
second_plural_noun= input("Give me another plural noun ")
third_plural_noun= input("Give me yet another plural noun ")
person= input("Give me a relationship ie. my: sister, BFF, gym teacher, physician ")
verb= input("Give me an emotion verb ie. love, like ")
second_adjective= input("Give me an adjective ending in -est ")
print ("Dear "+ celebrity + ",")
print(" I am writing this letter because I am a " + first_adjective+ " fan." +" Your " + first_noun +" really inspires me and I hope someday I too can become a "+ second_noun + " just like you. I own all of your "+ first_plural_noun +", I am your biggest "+ third_noun + ". I remember the first time I "+ past_verb+ " your "+ fourth_noun+ " I instantly loved you. I ran to tell my " + person + " how much I " + verb+ " you. I love you more than " + second_plural_noun +" and "+ third_plural_noun + " combined. " )
print("              Love your " + second_adjective + " fan!" )
